# Generated by Django 6.0.1 on 2026-01-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Введите краткое содержание', verbose_name='Описание книги'),
        ),
    ]
